name: CIFuzz
on: [pull_request]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: hartwork/oss-fuzz/infra/cifuzz/actions/build_fuzzers@issue-10472-debugging
      with:
        oss-fuzz-project-name: 'usbguard'
    - name: Run Fuzzers
      uses: hartwork/oss-fuzz/infra/cifuzz/actions/run_fuzzers@issue-10472-debugging
      with:
        oss-fuzz-project-name: 'usbguard'
        fuzz-seconds: 10
    - name: Upload Crash
      uses: actions/upload-artifact@v3
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
